articles/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /article/5/
    url(r'^(?P<pk>[0-9]+)/$', views.ArticleView.as_view(), name='article'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exercise/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'exercise.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^index/', include('articles.urls', namespace="index")),
    url(r'^admin/', include(admin.site.urls)),
]

articles/models.py
from django.db import models

class Article(models.Model):
    article_title = models.CharField(max_length=200)
    article_author = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    article_category = models.CharField(max_length=200)
    article_hero = models.ImageField(upload_to="articles")
    article_img = models.ImageField(upload_to="articles", blank=True, null=True)
    article_body = models.TextField()

    def __unicode__(self):
        return self.article_title

articles/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone


from .models import Article


class IndexView(generic.ListView):
    template_name = 'articles/index.html'
    context_object_name = 'article_list'
    random_article = Article.objects.order_by('?')[0]

    def get_queryset(self):
        """Return all articles"""
        return Article.objects.order_by('-pub_date').filter(pub_date__lte=timezone.now())

class ArticleView(generic.DetailView):
    model = Article
    template_name = 'articles/article.html'


# def article(request, article_id):
#     try:
#         article = Articles.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Article does not exist")
#     return render(request, 'articles/article.html', {'article': article})

articles/templates/articles/article.html
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}"
          rel="stylesheet" media="screen">
    <link rel="stylesheet" type="text/css" href="{% static 'articles/style.css' %}" />
    <link href="{% static 'font-awesome-4.3.0/css/font-awesome.min.css' %}"
          rel="stylesheet" media="screen">
  </head>

  <body>
    <div id="wrapper">


      <!-- Sidebar -->
      <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
              <li class="sidebar-brand">
                  <a href="/index/">
                      Gale Exercise
                  </a>
              </li>
              <li>
                  <a href="#">Link 1</a>
              </li>
              <li>
                  <a href="#">Link 2</a>
              </li>
              <li>
                  <a href="#">Link 3</a>
              </li>
              <li>
                  <a href="#">Link 4</a>
              </li>
              <li>
                  <a href="#">Link 5</a>
              </li>
          </ul>
      </div>
      <!-- /#sidebar-wrapper -->
      <a href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars fa-2x"></i></a>


      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              <h1>{{ article.article_title }}</h1>
              <p id="date-author">{{ article.pub_date|date:"l, F jS, Y" }} | {{ article.article_author }}</p>
              <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive"/>
            </div>
          </div>
          <div class="row" id="paragraph">
            {% if article.article_img %}
            <div class="col-md-8 col-lg-6">
              <p>
                {{ article.article_body|linebreaks}}
              </p>
            </div>
            <div class="col-md-4 col-lg-6">
              <img src="/index{{ article.article_img.url }}" alt="" class="img-responsive"/>
            </div>
            {% else %}
            <div class="col-lg-12">
              <textarea>
                {{ article.article_body}}
              </textarea>
            </div>
            {% endif %}
          </div>
          <div class="row">
            <div class="col-lg-12">
              <hr>
              <h2>Read More</h2>
              <hr>
            </div>
          </div>
          <div class="row" id="read-more">
            <div class="col-xs-6 col-sm-6 col-md-3">
              {% with article_list|random as article %}
              <a href="{% url 'index:article' article.id %}">
                <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive"/>
                <h5>{{ article.article_title }}</h5>
              </a>
              {% endwith %}
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3">
              {% with article_list|random as article %}
              <a href="{% url 'index:article' article.id %}">
                <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive"/>
                <h5>{{ article.article_title }}</h5>
              </a>
              {% endwith %}
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3">
              {% with article_list|random as article %}
              <a href="{% url 'index:article' article.id %}">
                <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive"/>
                <h5>{{ article.article_title }}</h5>
              </a>
              {% endwith %}
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3">
              {% with article_list|random as article %}
              <a href="{% url 'index:article' article.id %}">
                <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive"/>
                <h5>{{ article.article_title }}</h5>
              </a>
              {% endwith %}
            </div>
          </div>
        </div>
      </div>
      <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->


    <script src="{% static 'jquery/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>


  </body>
</html>

articles/templates/articles/article_list.html
{% extends "index.html" %}

{% block content %}


{% endblock %}

articles/templates/articles/index.html
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}"
          rel="stylesheet" media="screen">
    <link rel="stylesheet" type="text/css" href="{% static 'articles/style.css' %}" />
    <link href="{% static 'font-awesome-4.3.0/css/font-awesome.min.css' %}"
          rel="stylesheet" media="screen">
  </head>

  <body>
    <div id="wrapper">


      <!-- Sidebar -->
      <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
              <li class="sidebar-brand">
                  <a href="/index/">
                      Gale Exercise
                  </a>
              </li>
              <li>
                  <a href="#">Link 1</a>
              </li>
              <li>
                  <a href="#">Link 2</a>
              </li>
              <li>
                  <a href="#">Link 3</a>
              </li>
              <li>
                  <a href="#">Link 4</a>
              </li>
              <li>
                  <a href="#">Link 5</a>
              </li>
          </ul>
      </div>
      <!-- /#sidebar-wrapper -->
      <a href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars fa-2x"></i></a>


      <div id="page-content-wrapper">
        <div class="container-fluid">
          <div class="row">
            <div class="col-lg-12">
              {% with article_list|random as article %}
              <h2>{{ article.article_title }}</h2>
              <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive random-hero"/>
              <p>{{ article.article_body|truncatechars:400 }}</p>
              {% endwith %}
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <ol id="article-list">
                {% for article in article_list %}
                  <li>
                    <h3>{{ article.article_title }}</h3>
                    <p>{{ article.article_body|truncatechars:400 }}</p>
                    <a href="{% url 'index:article' article.id %}">Read more</a>
                  </li>
                {% endfor %}
              </ol>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <hr>
              <h2>Read More</h2>
              <hr>
            </div>
          </div>
          <div class="row" id="read-more">
            <div class="col-xs-6 col-sm-6 col-md-3">
              {% with article_list|random as article %}
              <a href="{% url 'index:article' article.id %}">
                <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive"/>
                <h5>{{ article.article_title }}</h5>
              </a>
              {% endwith %}
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3">
              {% with article_list|random as article %}
              <a href="{% url 'index:article' article.id %}">
                <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive"/>
                <h5>{{ article.article_title }}</h5>
              </a>
              {% endwith %}
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3">
              {% with article_list|random as article %}
              <a href="{% url 'index:article' article.id %}">
                <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive"/>
                <h5>{{ article.article_title }}</h5>
              </a>
              {% endwith %}
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3">
              {% with article_list|random as article %}
              <a href="{% url 'index:article' article.id %}">
                <img src="/index{{ article.article_hero.url }}" alt=""  class="img-responsive"/>
                <h5>{{ article.article_title }}</h5>
              </a>
              {% endwith %}
            </div>
          </div>
        </div>
      </div>
      <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->


    <script src="{% static 'jquery/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>


  </body>
</html>